// import './globals.css';
// import { GlobalStateProvider } from '../context/global-context';
// import Header from '../components/header/header.component';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
 
// export default function RootLayout({ children }) {
//  return (
//     <html lang="en">
//       <body>
//         <GlobalStateProvider>
//           HERE
//             {children}
//         </GlobalStateProvider>
//       </body>
//     </html>
//   )
// }
